### ISSUE TITLE
optPathVisualizer

### ISSUE THREAD

**Issue by waxeia** [magmaOffenburg/magmaRelease#2]
![截图 2024-04-25 16-28-20](https://github.com/magmaOffenburg/magmaRelease/assets/121557616/25ecee05-3556-4327-b096-60160d6de7e0)
It is in [https://github.com/magmaOffenburg/magmaRelease/blob/main/magmaagent/src/main/java/magma/agent/decision/behavior/complex/path/OptimalPathCalculation.java](url)
magmaagent/src/main/java/magma/agent/decision/behavior/complex/path/OptimalPathCalculation.java
I can't find the dependency named optPathVisualizer in my IntelliJ IDEA and I also search it online. But find nothing.
Hello, I need some help for this problem. I can't fix it by myself because of my limited ability. I really hope that you can give me some help or advice to fix it. I am very grateful to you! Have a good day!

**Comment by hannesbraun** [comment]
Well, this was commented out by us for a reason, even in our own (unreleased) code base. Importing it would violate our architecture. Right now, we don't have a solution either. But the class resides in some unreleased package of ours anyway. So you can't really do anything about it other than leaving it as it is.

**Comment by waxeia** [comment]
Thinks anyway. :smile:
